In [1]:
import numpy as np
import pandas as pd

In [2]:
import xlrd
import os

In [3]:
df=pd.read_excel('survey_dataset.xls')

In [4]:
def quali_to_numeric(x):
    if x=='SSLC':
        return 1
    if x=='Plus Two':
        return 2
    if x=='Graduation':
        return 3
    if x=='PG':
        return 4
    else :
        return 0
    
def country_to_numeric(x):
    if x=='America':
        return 5
    else:
        return 3

In [5]:
df['Qualification'] = df['Qualification'].apply(quali_to_numeric)
df['Country'] = df['Country'].apply(country_to_numeric)
df

,Reader_id,Gender,Age,Qualification,Country,Income,Political biasness(1-10),Article1_bias,Article1_type_bias,Article1_political_rank,...,Article2_political_rank,Article3_bias,Article3_type_bias,Article3_political_rank,Article4_bias,Article4_type_bias,Article4_political_rank,Article5_bias,Article5_type_bias,Article5_political_rank
0,1,Male,65,3,5,50000,4,2,Other bias,1,...,7,3,corporate bias,7,2,political bias,4,2,NaN,0
1,2,Male,32,1,3,20000,3,3,Political bias,3,...,8,7,Political bias,6,7,Person Bias,3,7,Political bias,3
2,3,Female,41,4,5,80000,5,2,Other bias,2,...,7,0,corporate bias,7,0,political bias,4,0,NaN,0
3,4,Female,33,4,5,120000,4,2,Other bias,3,...,7,4,corporate bias,7,4,political bias,4,4,NaN,0
4,5,Female,65,4,3,30000,4,4,Product Bias,1,...,7,7,Product Bias,8,7,Person Bias,7,7,Other Bias,4
5,6,Female,69,1,3,12000,5,6,Product Bias,1,...,8,6,Product Bias,8,6,Person Bias,4,3,Other Bias,2
6,7,Female,35,3,3,25000,6,4,Product Bias,4,...,6,3,Product Bias,7,3,political bias,3,3,Political bias,1
7,8,Female,25,2,3,15000,3,3,Political bias,4,...,8,4,Political bias,8,2,political bias,3,3,Political bias,2
8,9,Female,23,2,3,10000,5,3,Product Bias,6,...,8,4,Product Bias,6,4,political bias,2,3,Political bias,2
9,10,Female,22,3,3,50000,9,4,Political bias,4,...,8,7,Product Bias,6,7,Person Bias,3,7,NaN,0
10,11,Female,21,0,3,28000,7,2,Corporate bias,4,...,8,3,Political bias,4,3,Person Bias,4,3,NaN,0
11,12,Female,18,3,3,25000,2,4,Social Bias,2,...,9,3,corporate bias,6,3,Product Bias,4,4,NaN,0
12,13,Female,19,3,3,15000,1,4,Product Bias,3,...,6,4,Political bias,3,3,political bias,3,4,Political bias,9
13,14,Female,20,2,3,10000,6,4,Product Bias,3,...,3,6,Political bias,8,3,Person Bias,2,2,Other Bias,1
14,15,Female,30,3,3,25000,5,4,Political bias,3,...,7,4,Product Bias,9,2,Person Bias,3,2,Political bias,1
15,16,Female,41,1,3,30000,8,4,Political bias,4,...,5,3,Product Bias,8,3,political bias,4,3,Other Bias,2
16,17,Female,52,3,3,12000,6,4,Product Bias,4,...,6,4,Product Bias,7,4,political bias,3,4,Political bias,3
17,18,Female,48,4,3,50000,5,2,Other bias,2,...,7,7,corporate bias,7,7,political bias,4,7,NaN,0
18,19,Female,52,1,3,2000,4,3,Political bias,4,...,8,3,Political bias,8,3,political bias,3,3,Political bias,0
19,20,Female,18,1,3,10000,3,3,Political bias,3,...,8,8,Political bias,6,4,Person Bias,3,4,Political bias,1
20,21,Female,19,2,3,12000,9,3,Other bias,2,...,6,4,Political bias,7,4,political bias,4,4,Other Bias,2
21,22,Female,32,4,3,20000,6,2,Other bias,2,...,7,3,corporate bias,7,3,political bias,4,3,NaN,1
22,23,Female,33,4,3,23000,8,4,Product Bias,1,...,7,3,Product Bias,8,3,Person Bias,7,3,Other Bias,0
23,24,Female,25,3,3,30000,7,3,Political bias,3,...,6,2,Product Bias,6,2,Political bias,3,2,Political bias,2
24,25,Female,22,3,3,35000,7,4,Product Bias,4,...,7,2,Product Bias,7,2,Political bias,2,2,Political bias,1
25,26,Female,24,0,3,20000,5,2,Political bias,4,...,6,4,Political bias,6,4,Political bias,1,4,Other Bias,2
26,27,Male,29,1,3,8000,2,3,Product Bias,4,...,7,4,corporate bias,5,7,corporate bias,4,7,Other Bias,0
27,28,Female,30,2,3,10000,2,4,Product Bias,3,...,7,3,Political bias,3,3,corporate bias,6,3,Other Bias,2
28,29,Male,22,2,3,13000,2,4,Product Bias,3,...,7,4,Political bias,2,0,Political bias,4,0,Political bias,1
29,30,Female,54,1,3,12000,6,4,Political bias,2,...,8,3,Product Bias,7,3,Political bias,3,4,Other Bias,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,471,Male,55,0,3,10000,5,4,Political bias,3,...,8,4,person bias,7,3,person bias,3,3,Social Bias,2
471,472,Female,54,1,3,30000,9,3,Product Bias,4,...,9,3,Corporate bias,6,3,Socially Bias,2,3,Social Bias,2
472,473,Female,52,0,3,12000,8,7,Product Bias,4,...,5,7,person bias,7,2,person bias,3,2,NaN,2
473,474,Female,46,1,3,3000,8,7,Political bias,3,...,7,7,Socially Bias,7,7,Political bias,4,7,Social Bias,2
474,475,Male,65,1,3,12000,6,2,Other bias,2,...,7,4,Socially Bias,8,2,Corporate bias,3,2,Political bias,0
475,476,Male,63,4,3,50000,3,3,Political bias,3,...,8,3,person bias,9,3,Socially Bias,4,3,NaN,1
476,477,Male,25,4,3,32000,3,4,Political bias,4,...,6,4,person bias,7,4,person bias,3,4,Political bias,2
477,478,Female,27,4,3,50000,3,7,Other bias,3,...,6,2,Political bias,4,2,Corporate bias,3,2,Political bias,0
478,479,Female,28,1,3,8000,7,7,Political bias,3,...,7,4,person bias,8,7,person bias,4,0,Political bias,3
479,480,Female,55,3,3,12000,6,6,Political bias,4,...,7,6,Political bias,9,6,person bias,4,6,NaN,1
480,481,Male,45,2,3,15000,7,4,Political bias,3,...,9,4,Corporate bias,9,4,Product bias,7,4,Political bias,2
481,482,Male,42,2,3,8000,5,6,Other bias,3,...,7,6,Political bias,8,6,person bias,4,2,Social Bias,0
482,483,Male,23,3,3,10000,2,3,Product Bias,3,...,9,3,Socially Bias,7,3,person bias,3,3,NaN,3
483,484,Female,24,0,3,30000,3,7,Product Bias,2,...,7,7,person bias,7,3,Corporate bias,3,3,Social Bias,2
484,485,Female,25,1,3,12000,3,4,Other bias,4,...,7,3,person bias,6,3,person bias,2,3,Political bias,0
485,486,Male,22,0,3,50000,6,7,Product Bias,3,...,6,7,Socially Bias,7,3,Socially Bias,3,0,NaN,2
486,487,Male,27,1,3,12000,7,8,Political bias,2,...,6,8,person bias,8,8,person bias,4,8,Political bias,1
487,488,Male,46,1,3,5000,9,8,Other bias,3,...,7,3,Political bias,4,3,Socially Bias,4,3,Social Bias,0
488,489,Female,57,4,3,8000,5,3,Political bias,4,...,6,3,Socially Bias,6,3,person bias,3,3,Political bias,3
489,490,Female,60,3,3,20000,5,3,Political bias,3,...,6,6,Socially Bias,7,6,Political bias,2,6,NaN,2
490,491,Female,62,3,3,25000,5,4,Political bias,2,...,5,3,person bias,7,2,Corporate bias,3,2,NaN,3
491,492,Male,31,4,3,30000,7,8,Other bias,4,...,8,8,Socially Bias,6,8,Socially Bias,4,4,Social Bias,0
492,493,Male,43,1,3,12000,6,7,Other bias,2,...,8,7,Corporate bias,7,3,person bias,3,3,Political bias,0
493,494,Male,21,4,3,50000,5,2,Product Bias,2,...,6,4,Corporate bias,6,4,Corporate bias,4,4,Political bias,2
494,495,Female,35,4,3,12000,2,8,Political bias,2,...,8,4,person bias,8,4,person bias,3,4,NaN,3
495,496,Female,26,4,3,5000,3,3,Product Bias,4,...,7,3,Corporate bias,8,3,person bias,3,3,NaN,3
496,497,Male,54,1,3,8000,3,3,Other bias,2,...,6,3,person bias,6,3,Product bias,4,3,Political bias,0
497,498,Female,53,3,3,20000,6,3,Other bias,3,...,7,3,person bias,9,6,person bias,4,6,NaN,0
498,499,Female,60,2,3,25000,7,4,Political bias,3,...,8,3,person bias,8,3,person bias,7,3,Political bias,3
499,500,Male,39,2,3,30000,9,2,Political bias,3,...,8,2,person bias,7,2,Corporate bias,4,0,NaN,2

In [6]:
res1=df['Political biasness(1-10)']
res2=res1.append(df['Political biasness(1-10)'])
res3=res2.append(df['Political biasness(1-10)'])
res4=res3.append(df['Political biasness(1-10)'])
res5=res4.append(df['Political biasness(1-10)'])

In [7]:
res5.columns=['Political biasness(1-10)']
print(res5)
print(res5.columns)

0      4
1      3
2      5
3      4
4      4
5      5
6      6
7      3
8      5
9      9
10     7
11     2
12     1
13     6
14     5
15     8
16     6
17     5
18     4
19     3
20     9
21     6
22     8
23     7
24     7
25     5
26     2
27     2
28     2
29     6
      ..
470    5
471    9
472    8
473    8
474    6
475    3
476    3
477    3
478    7
479    6
480    7
481    5
482    2
483    3
484    3
485    6
486    7
487    9
488    5
489    5
490    5
491    7
492    6
493    5
494    2
495    3
496    3
497    6
498    7
499    9
Name: Political biasness(1-10), Length: 2500, dtype: int64
['Political biasness(1-10)']

In [8]:
y1=pd.DataFrame([5]*100)
y2=pd.DataFrame([4]*100)
y3=pd.DataFrame([3]*100)
y4=pd.DataFrame([2]*100)
y5=pd.DataFrame([1]*100)

In [9]:
f1=df[['Age','Income','Qualification','Country']]

In [10]:
f2=f1.append(f1)
f3=f2.append(f1)
f4=f3.append(f1)
f5=f4.append(f1)

In [11]:
f5

     Age  Income  Qualification  Country
0     65   50000              3        5
1     32   20000              1        3
2     41   80000              4        5
3     33  120000              4        5
4     65   30000              4        3
5     69   12000              1        3
6     35   25000              3        3
7     25   15000              2        3
8     23   10000              2        3
9     22   50000              3        3
10    21   28000              0        3
11    18   25000              3        3
12    19   15000              3        3
13    20   10000              2        3
14    30   25000              3        3
15    41   30000              1        3
16    52   12000              3        3
17    48   50000              4        3
18    52    2000              1        3
19    18   10000              1        3
20    19   12000              2        3
21    32   20000              4        3
22    33   23000              4        3
23    25   30000              3        3
24    22   35000              3        3
25    24   20000              0        3
26    29    8000              1        3
27    30   10000              2        3
28    22   13000              2        3
29    54   12000              1        3
..   ...     ...            ...      ...
470   55   10000              0        3
471   54   30000              1        3
472   52   12000              0        3
473   46    3000              1        3
474   65   12000              1        3
475   63   50000              4        3
476   25   32000              4        3
477   27   50000              4        3
478   28    8000              1        3
479   55   12000              3        3
480   45   15000              2        3
481   42    8000              2        3
482   23   10000              3        3
483   24   30000              0        3
484   25   12000              1        3
485   22   50000              0        3
486   27   12000              1        3
487   46    5000              1        3
488   57    8000              4        3
489   60   20000              3        3
490   62   25000              3        3
491   31   30000              4        3
492   43   12000              1        3
493   21   50000              4        3
494   35   12000              4        3
495   26    5000              4        3
496   54    8000              1        3
497   53   20000              3        3
498   60   25000              2        3
499   39   30000              2        3

[2500 rows x 4 columns]

In [12]:
result_matrix=res5
result_matrix.columns=['Political biasness(1-10)']
print(result_matrix)

0      4
1      3
2      5
3      4
4      4
5      5
6      6
7      3
8      5
9      9
10     7
11     2
12     1
13     6
14     5
15     8
16     6
17     5
18     4
19     3
20     9
21     6
22     8
23     7
24     7
25     5
26     2
27     2
28     2
29     6
      ..
470    5
471    9
472    8
473    8
474    6
475    3
476    3
477    3
478    7
479    6
480    7
481    5
482    2
483    3
484    3
485    6
486    7
487    9
488    5
489    5
490    5
491    7
492    6
493    5
494    2
495    3
496    3
497    6
498    7
499    9
Name: Political biasness(1-10), Length: 2500, dtype: int64

In [13]:
#from sklearn.preprocessing import MinMaxScaler



#scaler = MinMaxScaler()
numerical = ['Age']

features_minmax_transform = pd.DataFrame(data = f5)
features_minmax_transform[numerical] = f5[numerical]
features_minmax_transform

     Age  Income  Qualification  Country
0     65   50000              3        5
1     32   20000              1        3
2     41   80000              4        5
3     33  120000              4        5
4     65   30000              4        3
5     69   12000              1        3
6     35   25000              3        3
7     25   15000              2        3
8     23   10000              2        3
9     22   50000              3        3
10    21   28000              0        3
11    18   25000              3        3
12    19   15000              3        3
13    20   10000              2        3
14    30   25000              3        3
15    41   30000              1        3
16    52   12000              3        3
17    48   50000              4        3
18    52    2000              1        3
19    18   10000              1        3
20    19   12000              2        3
21    32   20000              4        3
22    33   23000              4        3
23    25   30000              3        3
24    22   35000              3        3
25    24   20000              0        3
26    29    8000              1        3
27    30   10000              2        3
28    22   13000              2        3
29    54   12000              1        3
..   ...     ...            ...      ...
470   55   10000              0        3
471   54   30000              1        3
472   52   12000              0        3
473   46    3000              1        3
474   65   12000              1        3
475   63   50000              4        3
476   25   32000              4        3
477   27   50000              4        3
478   28    8000              1        3
479   55   12000              3        3
480   45   15000              2        3
481   42    8000              2        3
482   23   10000              3        3
483   24   30000              0        3
484   25   12000              1        3
485   22   50000              0        3
486   27   12000              1        3
487   46    5000              1        3
488   57    8000              4        3
489   60   20000              3        3
490   62   25000              3        3
491   31   30000              4        3
492   43   12000              1        3
493   21   50000              4        3
494   35   12000              4        3
495   26    5000              4        3
496   54    8000              1        3
497   53   20000              3        3
498   60   25000              2        3
499   39   30000              2        3

[2500 rows x 4 columns]

In [14]:
features_final = pd.get_dummies(features_minmax_transform)
display(features_final.head(5))
encoded = list(features_final.columns)
#print ("{} total features after one-hot encoding.").format(len(encoded))

# The following line shows the encoded feature names
#print ("encoded")

   Age  Income  Qualification  Country
0   65   50000              3        5
1   32   20000              1        3
2   41   80000              4        5
3   33  120000              4        5
4   65   30000              4        3

In [15]:
features_final

     Age  Income  Qualification  Country
0     65   50000              3        5
1     32   20000              1        3
2     41   80000              4        5
3     33  120000              4        5
4     65   30000              4        3
5     69   12000              1        3
6     35   25000              3        3
7     25   15000              2        3
8     23   10000              2        3
9     22   50000              3        3
10    21   28000              0        3
11    18   25000              3        3
12    19   15000              3        3
13    20   10000              2        3
14    30   25000              3        3
15    41   30000              1        3
16    52   12000              3        3
17    48   50000              4        3
18    52    2000              1        3
19    18   10000              1        3
20    19   12000              2        3
21    32   20000              4        3
22    33   23000              4        3
23    25   30000              3        3
24    22   35000              3        3
25    24   20000              0        3
26    29    8000              1        3
27    30   10000              2        3
28    22   13000              2        3
29    54   12000              1        3
..   ...     ...            ...      ...
470   55   10000              0        3
471   54   30000              1        3
472   52   12000              0        3
473   46    3000              1        3
474   65   12000              1        3
475   63   50000              4        3
476   25   32000              4        3
477   27   50000              4        3
478   28    8000              1        3
479   55   12000              3        3
480   45   15000              2        3
481   42    8000              2        3
482   23   10000              3        3
483   24   30000              0        3
484   25   12000              1        3
485   22   50000              0        3
486   27   12000              1        3
487   46    5000              1        3
488   57    8000              4        3
489   60   20000              3        3
490   62   25000              3        3
491   31   30000              4        3
492   43   12000              1        3
493   21   50000              4        3
494   35   12000              4        3
495   26    5000              4        3
496   54    8000              1        3
497   53   20000              3        3
498   60   25000              2        3
499   39   30000              2        3

[2500 rows x 4 columns]

In [16]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(features_final, res5, train_size=0.80,random_state=1)

/home/devika/.local/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2069: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [17]:
X_train

     Age  Income  Qualification  Country
418   27   10000              1        3
199   44    8000              3        3
139   44   22000              3        3
2     41   80000              4        5
352   43   35000              3        3
495   26    5000              4        3
123   25   42000              3        3
287   32    3000              1        3
316   52    8000              2        3
421   34    8000              1        3
491   31   30000              4        3
179   23    5000              3        3
181   21   12000              3        3
146   52   22000              3        3
204   20   10000              2        3
210   42   30000              3        3
201   41   40000              3        3
186   30   20000              3        3
385   47   20000              4        3
249   25   25000              3        3
165   32   10000              3        3
16    52   12000              3        3
4     65   30000              4        3
27    30   10000              2        3
16    52   12000              3        3
200   42   10000              3        3
79    23   20000              3        3
392   32   25000              0        3
134   23   12000              2        3
310   42    3200              4        3
..   ...     ...            ...      ...
431   28   50000              2        3
228   19   24000              2        3
288   22   32000              4        3
257   24   10000              3        3
316   52    8000              2        3
420   32    5000              4        3
337   24   15000              1        3
319   30   32000              3        3
31    46   10000              3        3
25    24   20000              0        3
189   55    8000              0        3
110   45   30000              0        3
388   23    8000              3        3
27    30   10000              2        3
253   22   10000              3        3
62    33   12000              4        3
446   22   12000              4        3
168   33   23000              2        3
252   32   42000              3        3
357   21   32000              4        3
278   31   10000              2        3
300   60   32000              3        3
202   43   20000              2        3
129   55   20000              1        3
144   20   20000              3        3
460   22   80000              4        3
405   46   12000              4        3
96    26   15000              2        3
235   25   10000              1        3
61    32    8000              1        3

[2000 rows x 4 columns]

In [18]:
gnb = GaussianNB()

In [19]:
gnb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [21]:
y_pred = gnb.predict(X_test)
Accuracy=metrics.accuracy_score(y_test, y_pred)
Accuracy

0.186

In [22]:
predicted= gnb.predict([[55,25000,4,5]])

In [23]:
#predicted

In [24]:
print ("The reader political biasness is",predicted[0])

The reader political biasness is 4

In [25]:
if predicted[0]<5 :
    print("Right biased")
else :
    print("Left biased")

Right biased